homeassistant: 
  customize: !include includes/customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
automation: !include includes/automations.yaml
config:
frontend:
  themes: !include_dir_merge_named themes
history: !include includes/history.yaml
mobile_app:
person:
recorder: !include includes/recorder.yaml
script: !include includes/scripts.yaml
ssdp:
sun:
system_health:
system_log:
  fire_event: true
updater:

# Non-default items added
binary_sensor: !include includes/binarysensor.yaml
device_tracker: !include includes/devicetracker.yaml
group: !include includes/groups.yaml
http: !include includes/http.yaml
input_boolean: !include includes/inputboolean.yaml
input_number: !include includes/inputnumber.yaml
notify: !include includes/notify.yaml
scene: !include includes/scenes.yaml
sensor: !include includes/sensor.yaml
shell_command: !include includes/shellcommand.yaml
timer: !include includes/timer.yaml
variable: !include includes/variable.yaml
weather: !include includes/weather.yaml
zone: !include includes/zones.yaml
  
# Text to speech
tts:
  - platform: google_translate

logger:
  default: warning
  logs:
    NodeRed: debug
    # custom_components.sky_hub: debug
    # pyskyqremote.skyq_hub: debug
    custom_components.skyq: debug
    pyskyqremote.skyq_remote: debug
    # custom_components.dlink_hnap: debug
tplink:
  discovery: false
  switch:
    - host: !secret tplink_switch_1
    - host: !secret tplink_switch_2