homeassistant:
  customize:
    binary_sensor.tyrcelyn_tctv:
      friendly_name: TC TV
    binary_sensor.bluray:
      friendly_name: Sony Bluray
    sensor.tv_media_playing:
      friendly_name: "TV"
    
    media_player.tyrcelyn_tctv:
      friendly_name: "TCTV"         
media_player:
  - platform: braviatv_psk
    host: !secret tv_host
    psk: !secret tv_psk
    mac: !secret tv_mac
    amp: False
    android: True
    user_labels: True
    sourcefilter:
      - HDMI
    name: Tyrcelyn TCTV

template:
  - binary_sensor:
    - name: tyrcelyn_tctv
      unique_id: tyrcelyn_tctv
      state: "{{ is_state('media_player.tyrcelyn_tctv', 'on') }}"
    - name: bluray
      unique_id: bluray
      state: "{{ is_state('device_tracker.bluray', 'home') }}"
  - sensor:  
    - name: tv_media_playing
      unique_id: tv_media_playing
      state: >-
          {% if is_state('media_player.tyrcelyn_tctv', 'on')  %}
            {% if state_attr('media_player.tyrcelyn_tctv', 'media_title') != None %}
              {{ state_attr('media_player.tyrcelyn_tctv', 'media_title') }}
            {% else %}
              No info
            {% endif %}
          {% else %}
            Off
          {% endif %}
# sensor:
#   - platform: template
#     sensors:
#       tv_media_playing:
#         friendly_name: "TV"
#         value_template: >-
#           {% if is_state('media_player.tyrcelyn_tctv', 'on')  %}
#             {% if state_attr('media_player.tyrcelyn_tctv', 'media_title') != None %}
#               {{ state_attr('media_player.tyrcelyn_tctv', 'media_title') }}
#             {% else %}
#               No info
#             {% endif %}
#           {% else %}
#             Off
#           {% endif %}
# binary_sensor:
#   - platform: template
#     sensors:
#       tyrcelyn_tctv:
#         friendly_name: "TCTV"
#         value_template: "{{ is_state('media_player.tyrcelyn_tctv', 'on') }}"
#       bluray:
#         friendly_name: "Sony Bluray"
#         value_template: "{{ is_state('device_tracker.bluray', 'home') }}"

#    