#- platform: ping
#  name: internet
#  host: 8.8.8.8
#  scan_interval: 10

- platform: template
  sensors:
    presence_all:
      friendly_name: "TC - Presence - All"
      device_class: presence
      value_template: "{{ is_state('input_boolean.presence_all', 'on') }}"
    booking:
      friendly_name: "Bookings"
      device_class: presence
      value_template: "{{ is_state('input_boolean.booking', 'on') }}"
      
    internet:
      friendly_name: "Internet"
      device_class: connectivity
      value_template: "{{ is_state('input_boolean.internet', 'on') }}"
    garage_cam:
      friendly_name: "Garage Camera"
      device_class: connectivity
      value_template: "{{ is_state('input_boolean.garage_cam', 'on') }}"
    workshop_cam:
      friendly_name: "Workshop Camera"
      device_class: connectivity
      value_template: "{{ is_state('input_boolean.workshop_cam', 'on') }}"
