- platform: template
  sensors:
    presence_all:
      friendly_name: "Presence - All"
      device_class: presence
      value_template: "{{ is_state('input_boolean.presence_all', 'on') }}"
    presence_cleaner:
      friendly_name: "Presence - Cleaner"
      device_class: presence
      value_template: "{{ is_state('input_boolean.presence_cleaner', 'on') }}"
    booking:
      friendly_name: "Bookings"
      device_class: presence
      value_template: "{{ is_state('input_boolean.booking', 'on') }}"
      
    internet:
      friendly_name: "Internet"
      device_class: connectivity
      value_template: "{{ is_state('input_boolean.internet', 'on') }}"
    garage_cam:
      friendly_name: "Garage Camera"
      device_class: connectivity
      value_template: "{{ is_state('input_boolean.garage_cam', 'on') }}"
    workshop_cam:
      friendly_name: "Workshop Camera"
      device_class: connectivity
      value_template: "{{ is_state('input_boolean.workshop_cam', 'on') }}"

    bluray:
      friendly_name: "Sony Bluray"
      value_template: "{{ is_state('device_tracker.bluray', 'home') }}"

#    sky_uplink:
#      friendly_name: "Sky Uplink"
#      device_class: connectivity
#      value_template: "{{ is_state('device_tracker.sky_uplink', 'home') }}"

- platform: dlink_hnap
  name: Utility Motion
  host: !secret dlink_host
  type: motion
  username: !secret dlink_username
  password: !secret dlink_password
  timeout: 35

