- platform:  skyq
  name: Sky Q
  host: !secret skyq_host
  sources:
      BBCOne: '1,1,5'
      BBCTwo: '1,0,2'
      SkyAtlantic: '1,0,8'
      SkyOne: '1,0,6'
      SkyNews: '5,0,1'
      SkyF1: '4,0,6'
      CHup: 'channelup'                                                         #added
      CHdn: 'channeldown'                                                       #added
      Select: 'select'                                                          #added
      Up: 'up'                                                                  #added
      Down: 'down'                                                              #added
      Left: 'left'                                                              #added
      Right: 'right'                                                            #added
      I: 'i'                                                                    #added
      Dismiss: 'dismiss'                                                        #added
      Sidebar: 'Sidebar'                                                        #added
      Home: 'home'                                                              #added
      TVGuide: 'tvguide'                                                        #added
      Sky: 'sky'                                                                #added
      Record: 'record'                                                          #added
