- platform: systemmonitor
  resources:
    - type: processor_use
    - type: memory_free
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
  
- platform: template
  sensors:
    sky_media_content_type:
      friendly_name: "Media Content Type"
      value_template: "{{ state_attr('media_player.sky_q', 'media_content_type') }}"
    sky_media_title:
      friendly_name: "Media Title"
      value_template: "{{ state_attr('media_player.sky_q', 'media_title') }}"
    sky_media_channel:
      friendly_name: "Media Channel"
      value_template: "{{ state_attr('media_player.sky_q', 'media_channel') }}"
    sky_media_series_title:
      friendly_name: "Media Series Title"
      value_template: "{{ state_attr('media_player.sky_q', 'media_series_title') }}"
    sky_media_playing:
      friendly_name: "Sky Q Playing"
      value_template: >-
        {% if state_attr('media_player.sky_q', 'media_series_title') == None %}
          {{ state_attr('media_player.sky_q', 'media_channel') }}
        {% else %}
          {{ state_attr('media_player.sky_q', 'media_channel') }} - {{ state_attr('media_player.sky_q', 'media_series_title') }}
        {% endif %}
 
