- platform: darksky
  name: Home
  api_key: !secret darksky_key
  units: uk
  mode: daily
  scan_interval: 60
  latitude: !secret home_latitude
  longitude: !secret home_longitude

- platform: darksky
  name: Ty'r Celyn
  api_key: !secret darksky_key
  units: uk
  mode: daily
  scan_interval: 60
  latitude: !secret tc_latitude
  longitude: !secret tc_longitude
