binary_sensor:
  - platform: template
    sensors:
      booking:
        friendly_name: "Booked"
        device_class: presence
        value_template: "{{ is_state('input_boolean.booking', 'on') }}"

input_boolean:
  booking:
  
input_number:
  bookings_today:
    name: Bookings Today
    min: 0
    max: 10
  bookings_tomorrow:
    name: Bookings Tomorrow
    min: 0
    max: 10
  bookings_total:
    name: Bookings Total
    min: 0
    max: 10

shell_command:
  clean_knowndevices: /bin/bash /config/shell_scripts/clean_knowndevices.sh