binary_sensor:
  - platform: template
    sensors:
      booking:
        friendly_name: "Bookings"
        device_class: presence
        value_template: "{{ is_state('input_boolean.booking', 'on') }}"

input_boolean:
  booking:
  
input_number:
  bookings_today:
    name: Bookings Today
    min: 0
    max: 10
  bookings_tomorrow:
    name: Bookings Tomorrow
    min: 0
    max: 10
  bookings_total:
    name: Bookings Total
    min: 0
    max: 10

sensor:
  - platform: template
    sensors:
      bookings:
        value_template: "{{ states('binary_sensor.booking') }}"
        friendly_name_template: >-
          {% if is_state('binary_sensor.booking', 'on') %}
            Booked
          {% else %}
            Empty
          {% endif %}
        entity_picture_template: >-
          {% if is_state('binary_sensor.booking', 'on') %}
            /local/icons/home.png
          {% else %}
            /local/icons/home-outline.png
          {% endif %}

shell_command:
  clean_knowndevices: /bin/bash /config/shell_scripts/clean_knowndevices.sh