mqtt_discoverystream:
  base_topic: tyrcelyn
  discovery_topic: tyrcelyn-discovery
  publish_attributes: false
  publish_timestamps: false
  publish_discovery: true
  include:
    entities:
      - binary_sensor.tyrcelyn_presence_all
      - binary_sensor.tyrcelyn_presence_cleaner
      - sensor.tyrcelyn_bookings_today
      - sensor.tyrcelyn_bookings_tomorrow
      - sensor.tyrcelyn_bookings_total
      - binary_sensor.tyrcelyn_utility_room_motion
      - binary_sensor.tyrcelyn_living_room_motion
      - binary_sensor.tyrcelyn_gable_window
      - binary_sensor.tyrcelyn_tctv
      - binary_sensor.tyrcelyn_booking
      - sensor.tyrcelyn_sky_pin
      - sensor.tc_tv_current_power
      - sensor.tc_boiler_current_power
      - sensor.tc_tv_picture
      - sensor.tc_sunlight_opacity
      - binary_sensor.ev_charger
      - sensor.workshop_camera_voltage
      
homeassistant:
  customize:
    binary_sensor.tyrcelyn_protect_lr:
      friendly_name: "Protect"