media_player:
  - platform: braviatv_psk
    host: !secret tv_host
    psk: !secret tv_psk
    mac: !secret tv_mac
    amp: False
    android: True
    user_labels: True
    sourcefilter:
      - HDMI
    name: Tyrcelyn TCTV
    
sensor:
  - platform: template
    sensors:
      tv_media_playing:
        friendly_name: "TV"
        value_template: >-
          {% if is_state('media_player.tyrcelyn_tctv', 'on')  %}
            {% if state_attr('media_player.tyrcelyn_tctv', 'media_title') != None %}
              {{ state_attr('media_player.tyrcelyn_tctv', 'media_title') }}
            {% else %}
              No info
            {% endif %}
          {% else %}
            Off
          {% endif %}
binary_sensor:
  - platform: template
    sensors:
      tyrcelyn_tctv:
        friendly_name: "TCTV"
        value_template: "{{ is_state('media_player.tyrcelyn_tctv', 'on') }}"
      bluray:
        friendly_name: "Sony Bluray"
        value_template: "{{ is_state('device_tracker.bluray', 'home') }}"

homeassistant:
  customize:
    media_player.tyrcelyn_tctv:
      friendly_name: "TCTV"    