homeassistant:
  customize:
    sensor.hacs:
      unit_of_measurement: 'Updates'
      friendly_name: 'HACS'

sensor:
  - platform: websocket_api

  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: memory_free

  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
